# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 885c8cc9109ff35634af47dcec1ca67e3d53640f6a25ff32f33a0abcf71db21f
# rpm/host-runtime: b037782d2cefa64c6b88f75478081f85706ee6c7fe95f6e5c8b4092b464edabd
set(CMAKE_C_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/g++" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "/opt/rh/gcc-toolset-15/root/usr/bin/ar" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "/opt/rh/gcc-toolset-15/root/usr/bin/ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "/opt/rh/gcc-toolset-15/root/usr/bin/nm" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "/opt/rh/gcc-toolset-15/root/usr/bin/strip" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "/opt/rh/gcc-toolset-15/root/usr/bin/objcopy" CACHE FILEPATH "" FORCE)
set(CMAKE_READELF "/opt/rh/gcc-toolset-15/root/usr/bin/readelf" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "/opt/rh/gcc-toolset-15/root/usr/bin/ld" CACHE FILEPATH "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
