# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 9e79c71089e00c2fac15d4e8ecedd47b3405fe0d240baa9d964ab2aeffb5e411
# rpm/host-runtime: 15bebccbafc2f5b849de9b0f36ec694fb0cc829aebada4d936c1c595ec1ef029
set(CMAKE_CROSSCOMPILING OFF CACHE BOOL "" FORCE)
set(CMAKE_C_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/g++" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "/opt/rh/gcc-toolset-15/root/usr/bin/gcc" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "/opt/rh/gcc-toolset-15/root/usr/bin/ar" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "/opt/rh/gcc-toolset-15/root/usr/bin/ranlib" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "/opt/rh/gcc-toolset-15/root/usr/bin/nm" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "/opt/rh/gcc-toolset-15/root/usr/bin/strip" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "/opt/rh/gcc-toolset-15/root/usr/bin/objcopy" CACHE FILEPATH "" FORCE)
set(CMAKE_READELF "/opt/rh/gcc-toolset-15/root/usr/bin/readelf" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "/opt/rh/gcc-toolset-15/root/usr/bin/ld" CACHE FILEPATH "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)
