# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 38a352f70de4a7c247d27c7c52ed55c0226a596c6c9f849f79027328355e31b0
# vcpkg/sdk-build: 3ba5101626317b1d964205f50f567acc331b4f1cb95b57b32eef452aa277d320
# triplet: crossforge-arm64-el8-dynamic
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/crossforge/cmake/aarch64-unknown-linux-gnu.cmake")
set(VCPKG_C_FLAGS "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
