# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 38a352f70de4a7c247d27c7c52ed55c0226a596c6c9f849f79027328355e31b0
# vcpkg/sdk-build: f7d1512861d2fe1d998a2b6095a1c6835d41ab104d24cfcbe09310c654ad0ed1
# triplet: crossforge-x64-el8
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/crossforge/cmake/x86_64-unknown-linux-gnu.cmake")
set(VCPKG_C_FLAGS "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
