# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 9e79c71089e00c2fac15d4e8ecedd47b3405fe0d240baa9d964ab2aeffb5e411
# vcpkg/sdk-build: d9a2454538d62570ca6b67a19c08452a521bd46f191043f415297df8f5f0011e
# triplet: crossforge-host-x64-el8
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/crossforge/cmake/host-gts15.cmake")
set(VCPKG_C_FLAGS "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
