# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 885c8cc9109ff35634af47dcec1ca67e3d53640f6a25ff32f33a0abcf71db21f
# vcpkg/sdk-build: 92b091c99733a86da217ebdfd09e67884cae48002105ec722f0db89738dff23e
# triplet: crossforge-arm64-el8-dynamic
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/crossforge/cmake/aarch64-unknown-linux-gnu.cmake")
set(VCPKG_C_FLAGS "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
