# Generated by scripts/render-vcpkg-integration.py; do not edit.
# implementation/vcpkg-integration: 885c8cc9109ff35634af47dcec1ca67e3d53640f6a25ff32f33a0abcf71db21f
# vcpkg/sdk-build: c7d44523b4a7c1b2f181c9c379517d9c1fc78ae25bc1b188682d417aecb7448e
# triplet: crossforge-x64-el8-dynamic
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/crossforge/cmake/x86_64-unknown-linux-gnu.cmake")
set(VCPKG_C_FLAGS "-fPIC")
set(VCPKG_CXX_FLAGS "-fPIC")
