#!/usr/bin/env python3
"""Render Crossforge CMake toolchains and vcpkg overlay triplets."""

import argparse
import hashlib
import json
import runpy
import sys
from pathlib import Path


TOOLCHAIN_ROOT = Path("integration/cmake")
TRIPLET_ROOT = Path("integration/vcpkg/triplets")
MANIFEST_PATH = Path("integration/vcpkg/manifest.json")


class RenderError(RuntimeError):
    pass


def require(condition, message):
    if not condition:
        raise RenderError(message)


def header(integration_sha256, material_component, material_sha256):
    return (
        "# Generated by scripts/render-vcpkg-integration.py; do not edit.\n"
        "# implementation/vcpkg-integration: %s\n"
        "# %s: %s\n" % (
            integration_sha256,
            material_component,
            material_sha256,
        )
    )


def compiler_lines(prefix, triple=None):
    names = {
        "CMAKE_C_COMPILER": "gcc",
        "CMAKE_CXX_COMPILER": "g++",
        "CMAKE_ASM_COMPILER": "gcc",
        "CMAKE_AR": "ar",
        "CMAKE_RANLIB": "ranlib",
        "CMAKE_NM": "nm",
        "CMAKE_STRIP": "strip",
        "CMAKE_OBJCOPY": "objcopy",
        "CMAKE_READELF": "readelf",
        "CMAKE_LINKER": "ld",
    }
    result = []
    for variable, tool in names.items():
        executable = "%s/%s" % (prefix, tool if triple is None else triple + "-" + tool)
        result.append(
            'set(%s "%s" CACHE FILEPATH "" FORCE)' % (variable, executable)
        )
    if triple is not None:
        result.extend(
            (
                'set(CMAKE_C_COMPILER_AR "%s/%s-gcc-ar" CACHE FILEPATH "" FORCE)'
                % (prefix, triple),
                'set(CMAKE_C_COMPILER_RANLIB "%s/%s-gcc-ranlib" CACHE FILEPATH "" FORCE)'
                % (prefix, triple),
                'set(CMAKE_CXX_COMPILER_AR "%s/%s-gcc-ar" CACHE FILEPATH "" FORCE)'
                % (prefix, triple),
                'set(CMAKE_CXX_COMPILER_RANLIB "%s/%s-gcc-ranlib" CACHE FILEPATH "" FORCE)'
                % (prefix, triple),
            )
        )
    return result


def cmake_bool(value):
    require(isinstance(value, bool), "CMake boolean policy must be boolean")
    return "ON" if value else "OFF"


def render_host_toolchain(policy, integration_sha256, runtime_sha256):
    lines = [
        header(
            integration_sha256,
            "rpm/host-runtime",
            runtime_sha256,
        ).rstrip(),
        'set(CMAKE_CROSSCOMPILING %s CACHE BOOL "" FORCE)'
        % cmake_bool(policy["host"]["cross_compiling"]),
    ]
    lines.extend(
        compiler_lines(policy["host"]["compiler_root"])
    )
    lines.extend(
        (
            'set(CMAKE_POSITION_INDEPENDENT_CODE %s CACHE BOOL "" FORCE)'
            % cmake_bool(policy["position_independent_code"]),
            'set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)',
            'set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)',
            "",
        )
    )
    return "\n".join(lines)


def render_target_toolchain(
    policy,
    arch,
    target,
    integration_sha256,
    toolchain_sha256,
):
    triple = target["triple"]
    prefix = target["compiler_root"]
    sysroot = target["sysroot"]
    adapters = policy["execution_adapters"]
    modes = policy["find_root_modes"]
    lines = [
        header(
            integration_sha256,
            "toolchain/%s-build" % arch,
            toolchain_sha256,
        ).rstrip(),
        "if(DEFINED %s OR DEFINED ENV{%s})"
        % (adapters["cmake_variable"], adapters["environment_variable"]),
        '  message(FATAL_ERROR "Crossforge target toolchains forbid execution adapters")',
        "endif()",
        'set(CMAKE_SYSTEM_NAME "%s" CACHE STRING "" FORCE)'
        % policy["system_name"],
        'set(CMAKE_SYSTEM_VERSION "%s" CACHE STRING "" FORCE)'
        % policy["system_version"],
        'set(CMAKE_SYSTEM_PROCESSOR "%s" CACHE STRING "" FORCE)'
        % target["processor"],
        'set(CMAKE_SYSROOT "%s" CACHE PATH "" FORCE)' % sysroot,
        'set(CMAKE_FIND_ROOT_PATH "%s" CACHE STRING "" FORCE)' % sysroot,
        'set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM %s CACHE STRING "" FORCE)'
        % modes["program"],
        'set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY %s CACHE STRING "" FORCE)'
        % modes["library"],
        'set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE %s CACHE STRING "" FORCE)'
        % modes["include"],
        'set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE %s CACHE STRING "" FORCE)'
        % modes["package"],
    ]
    lines.extend(compiler_lines(prefix, triple))
    lines.extend(
        (
            'set(CMAKE_POSITION_INDEPENDENT_CODE %s CACHE BOOL "" FORCE)'
            % cmake_bool(policy["position_independent_code"]),
            'set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)',
            'set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF CACHE BOOL "" FORCE)',
            "",
        )
    )
    return "\n".join(lines)


def render_triplet(
    policy,
    name,
    architecture,
    linkage,
    toolchain,
    integration_sha256,
    sdk_sha256,
):
    return "\n".join(
        (
            header(
                integration_sha256,
                "vcpkg/sdk-build",
                sdk_sha256,
            ).rstrip(),
            "# triplet: %s" % name,
            "set(VCPKG_TARGET_ARCHITECTURE %s)" % architecture,
            "set(VCPKG_CRT_LINKAGE %s)" % policy["crt_linkage"],
            "set(VCPKG_LIBRARY_LINKAGE %s)" % linkage,
            "set(VCPKG_CMAKE_SYSTEM_NAME %s)" % policy["system_name"],
            'set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "%s/%s")'
            % (policy["cmake_root"], toolchain),
            'set(VCPKG_C_FLAGS "%s")' % policy["pic_flag"],
            'set(VCPKG_CXX_FLAGS "%s")' % policy["pic_flag"],
            "",
        )
    )


def render(repository):
    validator = runpy.run_path(str(repository / "scripts/validate-release.py"))
    component_renderer = runpy.run_path(
        str(repository / "scripts/render-release-components.py")
    )
    release = validator["load_json"](repository / "config/release.json")
    documents = component_renderer["render_documents"](
        repository=repository,
        release=release,
        implemented_rows=component_renderer["IMPLEMENTED_ROWS"],
    )
    drift = component_renderer["output_drift"](repository, documents)
    require(not drift, "release components are stale: %s" % "; ".join(drift))
    binding = documents[component_renderer["BINDING_PATH"]]
    digests = {
        record["component"]: record["canonical_sha256"]
        for record in binding["components"]
    }
    policy = component_renderer["VCPKG_INTEGRATION_POLICY"]
    targets = {target["arch"]: target for target in release["targets"]}
    require(
        set(targets) == set(policy["targets"]),
        "vcpkg policy/release target matrix differs",
    )
    integration_sha256 = digests["implementation/vcpkg-integration"]
    sdk_sha256 = digests["vcpkg/sdk-build"]
    outputs = {
        TOOLCHAIN_ROOT / policy["host"]["toolchain"]: render_host_toolchain(
            policy,
            integration_sha256,
            digests["rpm/host-runtime"],
        )
    }
    for arch in ("x86_64", "aarch64"):
        target = policy["targets"][arch]
        require(
            targets[arch]["triple"] == target["triple"],
            "%s vcpkg target triple differs from release" % arch,
        )
        outputs[TOOLCHAIN_ROOT / target["toolchain"]] = render_target_toolchain(
            policy,
            arch,
            target,
            integration_sha256,
            digests["toolchain/%s-build" % arch],
        )
        for linkage, triplet in (
            ("static", target["static_triplet"]),
            ("dynamic", target["dynamic_triplet"]),
        ):
            outputs[TRIPLET_ROOT / (triplet + ".cmake")] = render_triplet(
                policy,
                triplet,
                target["architecture"],
                linkage,
                target["toolchain"],
                integration_sha256,
                sdk_sha256,
            )
    host = policy["host"]
    outputs[TRIPLET_ROOT / (host["triplet"] + ".cmake")] = render_triplet(
        policy,
        host["triplet"],
        host["architecture"],
        host["library_linkage"],
        host["toolchain"],
        integration_sha256,
        sdk_sha256,
    )
    files = []
    for path, content in sorted(outputs.items(), key=lambda item: item[0].as_posix()):
        if path.parent == TOOLCHAIN_ROOT:
            installed = "cmake/" + path.name
        else:
            installed = "triplets/" + path.name
        files.append(
            {
                "path": installed,
                "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
            }
        )
    manifest = {
        "schema_version": 1,
        "kind": "crossforge-vcpkg-integration",
        "components": {
            "integration": {
                "component": "implementation/vcpkg-integration",
                "canonical_sha256": integration_sha256,
            },
            "sdk": {
                "component": "vcpkg/sdk-build",
                "canonical_sha256": sdk_sha256,
            },
        },
        "files": files,
        "policy": policy,
    }
    outputs[MANIFEST_PATH] = json.dumps(
        manifest, indent=2, sort_keys=True
    ) + "\n"
    return dict(sorted(outputs.items(), key=lambda item: item[0].as_posix()))


def output_drift(repository, outputs):
    drift = []
    expected_paths = {repository / path for path in outputs}
    for relative, expected in outputs.items():
        path = repository / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            drift.append("missing %s" % relative)
            continue
        if actual != expected:
            drift.append("stale %s" % relative)
    for root in (TOOLCHAIN_ROOT, TRIPLET_ROOT):
        directory = repository / root
        if not directory.exists():
            continue
        for path in directory.rglob("*"):
            if path not in expected_paths:
                drift.append("unexpected %s" % path.relative_to(repository))
    return sorted(drift)


def main():
    repository = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        outputs = render(repository)
        drift = output_drift(repository, outputs)
        if arguments.check:
            require(not drift, "; ".join(drift))
            print("valid: %d generated vcpkg integration files" % len(outputs))
            return 0
        for relative, content in outputs.items():
            path = repository / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        require(not output_drift(repository, outputs), "vcpkg output write drift")
        print("wrote: %d vcpkg integration files" % len(outputs))
        return 0
    except (KeyError, OSError, RenderError, TypeError, ValueError) as error:
        print("error: %s" % error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
